inherit_gem:
  jekyll: .rubocop.yml

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-sass-converter.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/IndentHeredoc:
  Exclude:
    - spec/**/*
