#!/bin/bash
echo "RuboCop $(bundle exec rubocop --version)"
bundle exec rubocop -D $@
success=$?
if ((success != 0)); then
   echo -e "\nTry running \`script/fmt --safe-auto-correct\` to automatically fix errors"
fi
exit $success
