#!/bin/bash

set -e

echo "Running rspec with sassc"
SASS_IMPLEMENTATION=sassc bundle exec rspec $@

if bundle exec gem list --silent --exact --installed sass-embedded; then
  echo "Running rspec with sass-embedded"
  SASS_IMPLEMENTATION=sass-embedded bundle exec rspec $@
fi
